based_on_package: example_robot_mock

hardware:
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
        # Use "mock" or "mujoco"
      - hardware_interface: "mujoco"
      - mujoco_viewer: "true"

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  # Overload with definition for FTS broadcaster
  config:
    package: "example_robot_sim"
    path: "config/control/ros2_controllers.yaml"
  # Overload to launch the FTS broadcaster
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "force_torque_sensor_broadcaster"
    - "joint_trajectory_admittance_controller"
    - "robotiq_gripper_controller"