hardware:
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "example_robot_mock"
      path: "urdf/r6_2f_proto1.urdf.xacro"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
        # Use "mock", "mujoco", or "real"
      - hardware_interface: "mock"
    srdf:
      package: "example_robot_mock"
      path: "config/moveit/r6_2f_proto1.srdf"

  # If the MoveIt Pro Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: True

  # If the MoveIt Pro Agent should launch the robot state publisher.
  # This should be false if you are launching the robot state publisher as part of drivers.
  # [Optional, default=True]
  launch_robot_state_publisher: True

  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware by changing a single parameter with config inheritance.
  # [Required]
  simulated: true

  # If simulated is true, launch the following file with the MoveIt Pro Agent:
  # [Optional, defaults to a blank launch file if not specified]
  simulated_hardware_launch_file:
    package: "moveit_studio_agent"
    path: "launch/blank.launch.py"

  # If simulated is true, launch the following file with the MoveIt Pro Drivers:
  # [Optional, defaults to a blank launch file if not specified]
  simulated_robot_driver_persist_launch_file:
    package: "moveit_studio_agent"
    path: "launch/blank.launch.py"

  # If simulated is false, launch the following file with the MoveIt Pro Drivers:
  # [Optional, defaults to a blank launch file if not specified]
  robot_driver_persist_launch_file:
    package: "moveit_studio_agent"
    path: "launch/blank.launch.py"

# Sets ROS global params for launch.
# [Optional]
ros_global_params:
  # Whether or not to use simulated time.
  # [Optional, default=False]
  use_sim_time: False

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "example_robot_mock"
    path: "config/control/ros2_controllers.yaml"
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    # - "force_torque_sensor_broadcaster"
    - "joint_trajectory_admittance_controller"
    - "robotiq_gripper_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    - "velocity_force_controller"
    - "joint_velocity_controller"
  # Any controllers here will not be spawned by MoveIt Pro.
  # [Optional, default=[]]
  controllers_not_managed: []
  # Optionally configure remapping rules to let multiple controllers receive commands on the same topic.
  # [Optional, default=[]]
  controller_shared_topics: []

objectives:
  objective_library_paths:
    example_objective:
      package_name: "example_robot_mock"
      relative_path: "objectives"
