<?xml version="1.0" ?>
<package format="3">
  <name>example_robot_sim</name>
  <version>0.0.1</version>
  <description>My robot configuration package</description>

  <maintainer email="support@picknik.ai">MoveIt Pro User</maintainer>
  <license>BSD-3-Clause</license>
  <license file="mjcf/assets/LICENSE">BSD-2-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>example_robot_mock</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
