controller_manager:
  ros__parameters:
    update_rate: 500 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    # force_torque_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    joint_trajectory_admittance_controller:
      type: joint_trajectory_admittance_controller/JointTrajectoryAdmittanceController
    velocity_force_controller:
      type: velocity_force_controller/VelocityForceController
    joint_velocity_controller:
      type: joint_velocity_controller/JointVelocityController
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

# Need to specify these because our MuJoCo robotiq has additional actuators
joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - robotiq_85_left_knuckle_joint
    interfaces:
      - position
      - velocity

# force_torque_sensor_broadcaster:
#   ros__parameters:
#     sensor_name: tcp_fts_sensor
#     state_interface_names:
#       - force.x
#       - force.y
#       - force.z
#       - torque.x
#       - torque.y
#       - torque.z
#     frame_id: tool0

joint_trajectory_admittance_controller:
  ros__parameters:
    # Joint group to control.
    planning_group_name: manipulator
    base_frame: base_link
    # The tip link of the kinematic chain, i.e. the frame that will be controlled.
    ee_frame: grasp_link
    # The frame where the force / torque sensor reading is given.
    # (Needs to exist in the kinematic chain).
    sensor_frame: ft_frame
    # The name of the force torque sensor in the robot description which will be used in the admittance calculation.
    # ft_sensor_name: tcp_fts_sensor
    # Joint accelerations chosen to match MoveIt configs.
    stop_accelerations:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 30.0

velocity_force_controller:
  ros__parameters:
    # Joint group to control.
    planning_group_name: manipulator
    # The tip link of the kinematic chain, i.e. the frame that will be controlled.
    ee_frame: grasp_link
    # The frame where the force / torque sensor reading is given.
    # (Needs to exist in the kinematic chain).
    sensor_frame: ft_frame
    # The name of the force torque sensor in the robot description which will be used in the admittance calculation.
    # ft_sensor_name: tcp_fts_sensor
    # Maximum joint-space velocities.
    max_joint_velocity:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    # Maximum joint-space accelerations.
    max_joint_acceleration:
      - 2.0
      - 2.0
      - 2.0
      - 2.0
      - 2.0
      - 2.0
    # Maximum Cartesian-space velocities.
    max_cartesian_velocity:
      - 0.25
      - 0.25
      - 0.25
      - 1.0
      - 1.0
      - 1.0
    # Maximum Cartesian-space accelerations.
    max_cartesian_acceleration:
      - 2.0
      - 2.0
      - 2.0
      - 4.0
      - 4.0
      - 4.0
    # Rate in Hz at which the controller will publish the state.
    state_publish_rate: 10
    # Damping coefficient for the Jacobian damped least-squares inverse.
    jacobian_damping: 0.005
    # Timeout in seconds after which the controller will stop motion if no new commands are received.
    command_timeout: 0.2
    # Padding (in radians) to add to joint position limits as a safety margin.
    joint_limit_position_tolerance: 0.02

joint_velocity_controller:
  ros__parameters:
    # Joint group to control.
    planning_group_name: manipulator
    # Maximum joint-space velocities.
    max_joint_velocity:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    # Maximum joint-space accelerations.
    max_joint_acceleration:
      - 2.0
      - 2.0
      - 2.0
      - 2.0
      - 2.0
      - 2.0
    command_interfaces: ["position"]
    # Padding (in radians) to add to joint position limits as a safety margin.
    joint_limit_position_tolerance: 0.02
    # Timeout in seconds after which the controller will stop motion if no new commands are received.
    command_timeout: 0.2
    # Rate in Hz at which the controller will publish the state.
    state_publish_rate: 20

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02

robotiq_activation_controller:
  ros__parameters:
    default: true
